<option value="Agama">Agama</option>
<option value="Agrikultur, Perhutanan & Perikanan">Agrikultur, Perhutanan & Perikanan</option>
<option value="Bahan-bahan (kayu, Kertas, Plastik, Kaca)">Bahan-bahan (kayu, Kertas, Plastik, Kaca)</option>
<option value="Bahasa Lain-lain">Bahasa Lain-lain</option>
<option value="Bangunan">Bangunan</option>
<option value="Biologi & Biokimia">Biologi & Biokimia</option>
<option value="Diagnostik Perubatan & Teknologi Rawatan">Diagnostik Perubatan & Teknologi Rawatan</option>
<option value="Elektrik & Tenaga">Elektrik & Tenaga</option>
<option value="Elektronik &automasi">Elektronik &automasi</option>
<option value="Farmasi">Farmasi</option>
<option value="Hotel, Restoran & Katering">Hotel, Restoran & Katering</option>
<option value="Jualan Borong & Runcit">Jualan Borong & Runcit</option>
<option value="Kejururawatan & Perjagaan">Kejururawatan & Perjagaan</option>
<option value="Kejururawatan & Penjagaan">Kejururawatan & Penjagaan</option>
<option value="Kejuruteraan & Kejuruteraan Awam">Kejuruteraan & Kejuruteraan Awam</option>
<option value="Kejuruteraan Awam">Kejuruteraan Awam</option>
<option value="Kesetiausahaan & Kerja Pejabat">Kesetiausahaan & Kerja Pejabat</option>
<option value="Kesihatan Pekerjaan Dan Keselamatan">Kesihatan Pekerjaan Dan Keselamatan</option>
<option value="Kewangan, Perbankan, Insurans">Kewangan, Perbankan, Insurans</option>
<option value="Kewartawanan & Pelaporan">Kewartawanan & Pelaporan</option>
<option value="Kimia Dan Proses">Kimia Dan Proses</option>
<option value="Latihan Untuk Guru-guru Pra-sekolah">Latihan Untuk Guru-guru Pra-sekolah</option>
<option value="Mathematics">Mathematics</option>
<option value="Mekanik & Kerja Logam">Mekanik & Kerja Logam</option>
<option value="Muzik & Seni Persembahan">Muzik & Seni Persembahan</option>
<option value="Pemasaran & Pengiklanan">Pemasaran & Pengiklanan</option>
<option value="Pembuatan & Pemprosesan">Pembuatan & Pemprosesan</option>
<option value="Pembuatan & Pemprosesan">Pembuatan & Pemprosesan</option>
<option value="Pemprosesan Makanan">Pemprosesan Makanan</option>
<option value="Pengeluaran Tanaman & Ternakan">Pengeluaran Tanaman & Ternakan</option>
<option value="Pengurusan & Pentadbiran">Pengurusan & Pentadbiran</option>
<option value="Perhutanan">Perhutanan</option>
<option value="Perikanan">Perikanan</option>
<option value="Perjalanan, Perlancongan & Percutian">Perjalanan, Perlancongan & Percutian</option>
<option value="Perniagaan & Pentadbiran">Perniagaan & Pentadbiran</option>
<option value="Perpustakaan, Informasi, Arkib">Perpustakaan, Informasi, Arkib</option>
<option value="Perundangan">Perundangan</option>
<option value="Reka Bentuk">Reka Bentuk</option>
<option value="Sains Aplikasi">Sains Aplikasi</option>
<option value="Sains Fizikal">Sains Fizikal</option>
<option value="Sains Komputer">Sains Komputer</option>
<option value="Sains Sosia & Tingkah Laku">Sains Sosia & Tingkah Laku</option>
<option value="Seni Bina & Perancangan Bandar">Seni Bina & Perancangan Bandar</option>
<option value="Seni Visual">Seni Visual</option>
<option value="Servis Pengangkutan">Servis Pengangkutan</option>
<option value="Statistik">Statistik</option>
<option value="Sukan">Sukan</option>
<option value="Sukan">Sukan</option>
<option value="Teknik Audio-visual & Pengeluaran Media">Teknik Audio-visual & Pengeluaran Media</option>
<option value="Terapi & Pemulihan">Terapi & Pemulihan</option>
<option value="Veterinari">Veterinari</option>
<option value="Lain-lain">Lain-lain</option>