<option value="University of Malaya">University of Malaya</option>
<option value="Universiti Teknologi Malaysia">Universiti Teknologi Malaysia</option>
<option value="Universiti Sains Malaysia">Universiti Sains Malaysia</option>
<option value="Universiti Putra Malaysia">Universiti Putra Malaysia</option>
<option value="Universiti Kebangsaan Malaysia">Universiti Kebangsaan Malaysia</option>
<option value="Universiti Malaysia Sabah">Universiti Malaysia Sabah</option>
<option value="Universiti Malaysia Sarawak">Universiti Malaysia Sarawak</option>
<option value="Universiti Malaysia Perlis">Universiti Malaysia Perlis</option>
<option value="Universiti Malaysia Pahang">Universiti Malaysia Pahang</option>
<option value="Universiti Malaysia Terengganu">Universiti Malaysia Terengganu</option>
<option value="Universiti Teknologi MARA">Universiti Teknologi MARA</option>
<option value="Universiti Utara Malaysia">Universiti Utara Malaysia</option>
<option value="Universiti Teknikal Malaysia Melaka">Universiti Teknikal Malaysia Melaka</option>
<option value="Universiti Malaysia Kelantan">Universiti Malaysia Kelantan</option>
<option value="Universiti Sultan Zainal Abidin">Universiti Sultan Zainal Abidin</option>
<option value="Universiti Pendidikan Sultan Idris">Universiti Pendidikan Sultan Idris</option>
<option value="Universiti Tun Hussein Onn Malaysia">Universiti Tun Hussein Onn Malaysia</option>
<option value="Universiti Malaysia Perak">Universiti Malaysia Perak</option>
<option value="Universiti Tunku Abdul Rahman">Universiti Tunku Abdul Rahman</option>
<option value="International Islamic University Malaysia">International Islamic University Malaysia</option>
<option value="Universiti Tenaga Nasional">Universiti Tenaga Nasional</option>
<option value="Universiti Kuala Lumpur">Universiti Kuala Lumpur</option>
<option value="Universiti Pertahanan Nasional Malaysia">Universiti Pertahanan Nasional Malaysia</option>
<option value="Universiti Islam Antarabangsa Malaysia">Universiti Islam Antarabangsa Malaysia</option>
<option value="Universiti Teknologi Petronas">Universiti Teknologi Petronas</option>
<option value="Universiti Malaysia Pahang">Universiti Malaysia Pahang</option>
<option value="Universiti Perguruan Sultan Idris">Universiti Perguruan Sultan Idris</option>
<option value="Universiti Teknologi Malaysia International Campus">Universiti Teknologi Malaysia International Campus</option>
<option value="Universiti Sultan Azlan Shah">Universiti Sultan Azlan Shah</option>
<option value="Universiti Darul Iman Malaysia">Universiti Darul Iman Malaysia</option>
<option value="Universiti Selangor">Universiti Selangor</option>
<option value="Wawasan Open University">Wawasan Open University</option>
<option value="Lain-lain">Lain-lain</option>
